# Generated by Django 4.1.6 on 2023-03-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="CustomUser",),
    ]
