# Generated by Django 4.1.6 on 2023-04-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_alter_customer_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="balance",
            field=models.DecimalField(decimal_places=3, max_digits=13),
        ),
    ]
